@echo off
php bin/console app:parse:csv GE:Festival
php bin/console app:parse:csv GE:Achievement
php bin/console app:parse:csv GE:ActiveHelp
php bin/console app:parse:csv GE:Actions
php bin/console app:parse:csv GE:AquariumFish
php bin/console app:parse:csv GE:Collectable
php bin/console app:parse:csv GE:CompanyCraft
php bin/console app:parse:csv GE:FishingSpot
php bin/console app:parse:csv GE:EquipmentImageBot
php bin/console app:parse:csv GE:Items
php bin/console app:parse:csv GE:KhloeShop
php bin/console app:parse:csv GE:Minions
php bin/console app:parse:csv GE:Mounts
php bin/console app:parse:csv GE:Quests
php bin/console app:parse:csv GE:Satisfaction
php bin/console app:parse:csv GE:SatisfactionTable
php bin/console app:parse:csv GE:SpecialShop
php bin/console app:parse:csv GE:TripleTriad
php bin/console app:parse:csv GE:Translator
php bin/console app:parse:csv GE:FishParameter
php bin/console app:parse:csv GE:Instances
php bin/console app:parse:csv GE:KeyItems
php bin/console app:parse:csv GE:RaceAbility
php bin/console app:parse:csv GE:Recipes
php bin/console app:parse:csv GE:Sightseeing
php bin/console app:parse:csv GE:Spearfish
php bin/console app:parse:csv GE:Storable
php bin/console app:parse:csv GE:BlueMageContent
php bin/console app:parse:csv GE:NpcsPagesAll
php bin/console app:parse:csv GE:Orchestrion
pause